"""empty message

Revision ID: a63bc281f7f8
Revises: 65b0dbc13dcb
Create Date: 2020-07-08 16:18:09.768439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63bc281f7f8'
down_revision = '65b0dbc13dcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prediction_tiles', 'quadkey_geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326),
               nullable=False)
    op.drop_index('idx_prediction_tiles_centroid', table_name='prediction_tiles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_prediction_tiles_centroid', 'prediction_tiles', ['centroid'], unique=False)
    op.alter_column('prediction_tiles', 'quadkey_geom',
               existing_type=geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326),
               nullable=True)
    # ### end Alembic commands ###
